"""edit supabse

Revision ID: c3dc3eda22f1
Revises: 
Create Date: 2025-11-25 18:40:24.631312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3dc3eda22f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatid', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('isBadWord', sa.Integer(), nullable=False),
    sa.Column('isBlock', sa.Boolean(), nullable=False),
    sa.Column('numberRequestsUnblock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chatid')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_isBadWord'), 'users', ['isBadWord'], unique=False)
    op.create_index(op.f('ix_users_numberRequestsUnblock'), 'users', ['numberRequestsUnblock'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_numberRequestsUnblock'), table_name='users')
    op.drop_index(op.f('ix_users_isBadWord'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
